window.esdocSearchIndex = [
  [
    "twist-site/@twist/core/src/decorators/abstract.jsx~abstract",
    "function/index.html#static-function-Abstract",
    "<span>Abstract</span> <span class=\"search-result-import-path\">twist-site/@twist/core/src/decorators/Abstract.jsx</span>",
    "function"
  ],
  [
    "twist-site/@twist/core/src/basestore.jsx~basestore",
    "class/@twist/core/src/BaseStore.jsx~BaseStore.html",
    "<span>BaseStore</span> <span class=\"search-result-import-path\">twist-site/@twist/core/src/BaseStore.jsx</span>",
    "class"
  ],
  [
    "twist-site/@twist/react/src/basevirtualcomponent.jsx~basevirtualcomponent",
    "class/@twist/react/src/BaseVirtualComponent.jsx~BaseVirtualComponent.html",
    "<span>BaseVirtualComponent</span> <span class=\"search-result-import-path\">twist-site/@twist/react/src/BaseVirtualComponent.jsx</span>",
    "class"
  ],
  [
    "twist-site/@twist/core/src/decorators/bind.jsx~bind",
    "function/index.html#static-function-Bind",
    "<span>Bind</span> <span class=\"search-result-import-path\">twist-site/@twist/core/src/decorators/Bind.jsx</span>",
    "function"
  ],
  [
    "twist-site/@twist/core/src/binder.jsx~binder",
    "class/@twist/core/src/Binder.jsx~Binder.html",
    "<span>Binder</span> <span class=\"search-result-import-path\">twist-site/@twist/core/src/Binder.jsx</span>",
    "class"
  ],
  [
    "twist-site/@twist/core/src/decorators/cache.jsx~cache",
    "function/index.html#static-function-Cache",
    "<span>Cache</span> <span class=\"search-result-import-path\">twist-site/@twist/core/src/decorators/Cache.jsx</span>",
    "function"
  ],
  [
    "twist-site/@twist/core/src/collectionbinder.jsx~collectionbinder",
    "class/@twist/core/src/CollectionBinder.jsx~CollectionBinder.html",
    "<span>CollectionBinder</span> <span class=\"search-result-import-path\">twist-site/@twist/core/src/CollectionBinder.jsx</span>",
    "class"
  ],
  [
    "twist-site/@twist/react/src/basecomponent.jsx~component",
    "class/@twist/react/src/BaseComponent.jsx~Component.html",
    "<span>Component</span> <span class=\"search-result-import-path\">twist-site/@twist/react/src/BaseComponent.jsx</span>",
    "class"
  ],
  [
    "twist-site/@twist/core/src/decorators/debounce.jsx~debounce",
    "function/index.html#static-function-Debounce",
    "<span>Debounce</span> <span class=\"search-result-import-path\">twist-site/@twist/core/src/decorators/Debounce.jsx</span>",
    "function"
  ],
  [
    "twist-site/@twist/core/src/decorators/delay.jsx~delay",
    "function/index.html#static-function-Delay",
    "<span>Delay</span> <span class=\"search-result-import-path\">twist-site/@twist/core/src/decorators/Delay.jsx</span>",
    "function"
  ],
  [
    "twist-site/@twist/core/src/disposable.jsx~disposable",
    "class/@twist/core/src/Disposable.jsx~Disposable.html",
    "<span>Disposable</span> <span class=\"search-result-import-path\">twist-site/@twist/core/src/Disposable.jsx</span>",
    "class"
  ],
  [
    "twist-site/@twist/core/src/decorators/memoize.jsx~memoize",
    "function/index.html#static-function-Memoize",
    "<span>Memoize</span> <span class=\"search-result-import-path\">twist-site/@twist/core/src/decorators/Memoize.jsx</span>",
    "function"
  ],
  [
    "twist-site/@twist/core/src/objectid.jsx~objectid",
    "class/@twist/core/src/ObjectId.jsx~ObjectId.html",
    "<span>ObjectId</span> <span class=\"search-result-import-path\">twist-site/@twist/core/src/ObjectId.jsx</span>",
    "class"
  ],
  [
    "twist-site/@twist/core/src/decorators/observable.jsx~observable",
    "function/index.html#static-function-Observable",
    "<span>Observable</span> <span class=\"search-result-import-path\">twist-site/@twist/core/src/decorators/Observable.jsx</span>",
    "function"
  ],
  [
    "twist-site/@twist/core/src/observablearray.jsx~observablearray",
    "class/@twist/core/src/ObservableArray.jsx~ObservableArray.html",
    "<span>ObservableArray</span> <span class=\"search-result-import-path\">twist-site/@twist/core/src/ObservableArray.jsx</span>",
    "class"
  ],
  [
    "twist-site/@twist/core/src/observablemap.jsx~observablemap",
    "class/@twist/core/src/ObservableMap.jsx~ObservableMap.html",
    "<span>ObservableMap</span> <span class=\"search-result-import-path\">twist-site/@twist/core/src/ObservableMap.jsx</span>",
    "class"
  ],
  [
    "twist-site/@twist/core/src/observableset.jsx~observableset",
    "class/@twist/core/src/ObservableSet.jsx~ObservableSet.html",
    "<span>ObservableSet</span> <span class=\"search-result-import-path\">twist-site/@twist/core/src/ObservableSet.jsx</span>",
    "class"
  ],
  [
    "twist-site/@twist/core/src/decorators/prototype.jsx~prototype",
    "function/index.html#static-function-Prototype",
    "<span>Prototype</span> <span class=\"search-result-import-path\">twist-site/@twist/core/src/decorators/Prototype.jsx</span>",
    "function"
  ],
  [
    "twist-site/@twist/core/src/scope.jsx~scope",
    "class/@twist/core/src/Scope.jsx~Scope.html",
    "<span>Scope</span> <span class=\"search-result-import-path\">twist-site/@twist/core/src/Scope.jsx</span>",
    "class"
  ],
  [
    "twist-site/@twist/core/src/signal.jsx~signal",
    "class/@twist/core/src/Signal.jsx~Signal.html",
    "<span>Signal</span> <span class=\"search-result-import-path\">twist-site/@twist/core/src/Signal.jsx</span>",
    "class"
  ],
  [
    "twist-site/@twist/core/src/signaldispatcher.jsx~signaldispatcher",
    "class/@twist/core/src/SignalDispatcher.jsx~SignalDispatcher.html",
    "<span>SignalDispatcher</span> <span class=\"search-result-import-path\">twist-site/@twist/core/src/SignalDispatcher.jsx</span>",
    "class"
  ],
  [
    "twist-site/@twist/core/src/decorators/state.jsx~state",
    "class/@twist/core/src/decorators/State.jsx~State.html",
    "<span>State</span> <span class=\"search-result-import-path\">twist-site/@twist/core/src/decorators/State.jsx</span>",
    "class"
  ],
  [
    "twist-site/@twist/core/src/decorators/throttle.jsx~throttle",
    "function/index.html#static-function-Throttle",
    "<span>Throttle</span> <span class=\"search-result-import-path\">twist-site/@twist/core/src/decorators/Throttle.jsx</span>",
    "function"
  ],
  [
    "twist-site/@twist/core/src/decorators/wrap.jsx~wrap",
    "function/index.html#static-function-Wrap",
    "<span>Wrap</span> <span class=\"search-result-import-path\">twist-site/@twist/core/src/decorators/Wrap.jsx</span>",
    "function"
  ],
  [
    "twist-site/@twist/core/src/middleware/protectormiddleware.jsx~protectormiddleware",
    "function/index.html#static-function-protectorMiddleware",
    "<span>protectorMiddleware</span> <span class=\"search-result-import-path\">twist-site/@twist/core/src/middleware/protectorMiddleware.jsx</span>",
    "function"
  ],
  [
    "twist-site/@twist/core/src/middleware/remotedevmiddleware.jsx~remotedevmiddleware",
    "function/index.html#static-function-remoteDevMiddleware",
    "<span>remoteDevMiddleware</span> <span class=\"search-result-import-path\">twist-site/@twist/core/src/middleware/remoteDevMiddleware.jsx</span>",
    "function"
  ],
  [
    "twist-site/@twist/core/src/decorators/state.jsx~state",
    "variable/index.html#static-variable-state",
    "<span>state</span> <span class=\"search-result-import-path\">twist-site/@twist/core/src/decorators/State.jsx</span>",
    "variable"
  ],
  [
    "twist-site/@twist/core/src/middleware/thunkmiddleware.jsx~thunkmiddleware",
    "function/index.html#static-function-thunkMiddleware",
    "<span>thunkMiddleware</span> <span class=\"search-result-import-path\">twist-site/@twist/core/src/middleware/thunkMiddleware.jsx</span>",
    "function"
  ],
  [
    "",
    "test-file/@twist/core/test/decorators/AbstractTest.jsx.html#lineNumber18",
    "@Abstract decorator",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/decorators/AbstractTest.jsx.html#lineNumber20",
    "@Abstract decorator sanity check",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/decorators/ActionTest.jsx.html#lineNumber22",
    "@Action decorator",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/decorators/ActionTest.jsx.html#lineNumber78",
    "@Action decorator @Action can dispatch another action",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/decorators/ActionTest.jsx.html#lineNumber97",
    "@Action decorator @Action cannot dispatch an asynchronous action",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/decorators/ActionTest.jsx.html#lineNumber24",
    "@Action decorator @Action not allowed on a class",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/decorators/ActionTest.jsx.html#lineNumber49",
    "@Action decorator @Action not allowed on a non-Store",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/decorators/ActionTest.jsx.html#lineNumber36",
    "@Action decorator @Action not allowed on a property that's not a method",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/decorators/ActionTest.jsx.html#lineNumber118",
    "@Action decorator ActionDispatcher gives an error if start and end don't match",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/decorators/BindTest.jsx.html#lineNumber18",
    "@Bind decorator",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/decorators/BindTest.jsx.html#lineNumber20",
    "@Bind decorator sanity check",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/decorators/CacheTest.jsx.html#lineNumber20",
    "@Cache decorator",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/decorators/CacheTest.jsx.html#lineNumber63",
    "@Cache decorator @Cache can only be used in a Disposable class",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/decorators/CacheTest.jsx.html#lineNumber22",
    "@Cache decorator @Cache can only be used on a getter",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/decorators/CacheTest.jsx.html#lineNumber42",
    "@Cache decorator @Cache cannot be used on a static getter",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/decorators/CacheTest.jsx.html#lineNumber121",
    "@Cache decorator Cache decorator - should update eagerly when binding changes, if there's a Binder.mutator",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/decorators/CacheTest.jsx.html#lineNumber83",
    "@Cache decorator Cache decorator - should update when binding changes",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/decorators/DebounceTest.jsx.html#lineNumber18",
    "@Debounce decorator",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/decorators/DebounceTest.jsx.html#lineNumber20",
    "@Debounce decorator sanity check",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/decorators/DelayTest.jsx.html#lineNumber19",
    "@Delay decorator",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/decorators/DelayTest.jsx.html#lineNumber21",
    "@Delay decorator sanity check",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/decorators/MemoizeTest.jsx.html#lineNumber18",
    "@Memoize decorator",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/decorators/MemoizeTest.jsx.html#lineNumber20",
    "@Memoize decorator sanity check",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/decorators/PrototypeTest.jsx.html#lineNumber18",
    "@Prototype decorator",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/decorators/PrototypeTest.jsx.html#lineNumber20",
    "@Prototype decorator sanity check",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/decorators/StateTest.jsx.html#lineNumber24",
    "@State.XXX decorators",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/decorators/StateTest.jsx.html#lineNumber450",
    "@State.XXX decorators @State.alias",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/decorators/StateTest.jsx.html#lineNumber151",
    "@State.XXX decorators @State.byArray(true)",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/decorators/StateTest.jsx.html#lineNumber91",
    "@State.XXX decorators @State.byBooleanVal",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/decorators/StateTest.jsx.html#lineNumber251",
    "@State.XXX decorators @State.byCustomRef",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/decorators/StateTest.jsx.html#lineNumber365",
    "@State.XXX decorators @State.byCustomRefArray",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/decorators/StateTest.jsx.html#lineNumber171",
    "@State.XXX decorators @State.byCustomVal",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/decorators/StateTest.jsx.html#lineNumber112",
    "@State.XXX decorators @State.byNumberVal",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/decorators/StateTest.jsx.html#lineNumber225",
    "@State.XXX decorators @State.byOptionalRef",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/decorators/StateTest.jsx.html#lineNumber199",
    "@State.XXX decorators @State.byRef",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/decorators/StateTest.jsx.html#lineNumber285",
    "@State.XXX decorators @State.byRefArray",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/decorators/StateTest.jsx.html#lineNumber409",
    "@State.XXX decorators @State.byRefMap",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/decorators/StateTest.jsx.html#lineNumber131",
    "@State.XXX decorators @State.bySimpleVal",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/decorators/StateTest.jsx.html#lineNumber26",
    "@State.XXX decorators @State.byVal - import and export",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/decorators/StateTest.jsx.html#lineNumber48",
    "@State.XXX decorators @State.byVal - import and export should stick to defined values",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/decorators/StateTest.jsx.html#lineNumber64",
    "@State.XXX decorators @State.byVal - should work with common names",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/decorators/TaskTest.jsx.html#lineNumber20",
    "@Task decorator",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/decorators/TaskTest.jsx.html#lineNumber22",
    "@Task decorator sanity check",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/decorators/ThrottleTest.jsx.html#lineNumber18",
    "@Throttle decorator",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/decorators/ThrottleTest.jsx.html#lineNumber20",
    "@Throttle decorator sanity check",
    "test"
  ],
  [
    "@twist/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "@twist/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "@twist/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "@twist/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "@twist/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "@twist/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "@twist/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "@twist/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "@twist/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "@twist/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "@twist/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "@twist/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "@twist/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "@twist/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "@twist/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "@twist/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "@twist/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "@twist/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "@twist/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "@twist/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "@twist/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "@twist/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "@twist/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "@twist/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "@twist/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "@twist/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "@twist/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "@twist/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "@twist/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "@twist/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "@twist/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "@twist/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "@twist/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "@twist/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "@twist/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "@twist/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "@twist/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "@twist/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "@twist/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "@twist/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "@twist/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "@twist/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "@twist/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "@twist/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "@twist/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "@twist/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "@twist/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "@twist/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "@twist/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "@twist/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "@twist/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "@twist/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "@twist/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "@twist/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "@twist/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "@twist/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "@twist/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "@twist/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "@twist/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "@twist/.external-ecmascript.js~String",
    "external"
  ],
  [
    "@twist/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "@twist/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "@twist/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "@twist/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "@twist/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "@twist/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "@twist/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "@twist/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "@twist/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "@twist/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "@twist/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "@twist/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "@twist/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "@twist/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "@twist/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "@twist/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "@twist/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "@twist/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "@twist/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "@twist/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "@twist/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "@twist/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "@twist/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "@twist/.external-ecmascript.js~function",
    "external"
  ],
  [
    "@twist/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "@twist/.external-ecmascript.js~null",
    "external"
  ],
  [
    "@twist/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "@twist/.external-ecmascript.js~number",
    "external"
  ],
  [
    "@twist/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "@twist/.external-ecmascript.js~object",
    "external"
  ],
  [
    "@twist/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "@twist/.external-ecmascript.js~string",
    "external"
  ],
  [
    "@twist/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "@twist/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "@twist/babel-plugin-transform-react/src/transformer.js",
    "file/@twist/babel-plugin-transform-react/src/Transformer.js.html",
    "@twist/babel-plugin-transform-react/src/Transformer.js",
    "file"
  ],
  [
    "@twist/babel-plugin-transform-react/src/index.js",
    "file/@twist/babel-plugin-transform-react/src/index.js.html",
    "@twist/babel-plugin-transform-react/src/index.js",
    "file"
  ],
  [
    "@twist/babel-plugin-transform-react/src/runtime/classes.js",
    "file/@twist/babel-plugin-transform-react/src/runtime/classes.js.html",
    "@twist/babel-plugin-transform-react/src/runtime/classes.js",
    "file"
  ],
  [
    "@twist/babel-plugin-transform-react/src/runtime/styles.js",
    "file/@twist/babel-plugin-transform-react/src/runtime/styles.js.html",
    "@twist/babel-plugin-transform-react/src/runtime/styles.js",
    "file"
  ],
  [
    "@twist/babel-plugin-transform-react/src/transforms/arrowliftingtransform.js",
    "file/@twist/babel-plugin-transform-react/src/transforms/ArrowLiftingTransform.js.html",
    "@twist/babel-plugin-transform-react/src/transforms/ArrowLiftingTransform.js",
    "file"
  ],
  [
    "@twist/babel-plugin-transform-react/src/transforms/asattributetransform.js",
    "file/@twist/babel-plugin-transform-react/src/transforms/AsAttributeTransform.js.html",
    "@twist/babel-plugin-transform-react/src/transforms/AsAttributeTransform.js",
    "file"
  ],
  [
    "@twist/babel-plugin-transform-react/src/transforms/bindattributetransform.js",
    "file/@twist/babel-plugin-transform-react/src/transforms/BindAttributeTransform.js.html",
    "@twist/babel-plugin-transform-react/src/transforms/BindAttributeTransform.js",
    "file"
  ],
  [
    "@twist/babel-plugin-transform-react/src/transforms/classattributetransform.js",
    "file/@twist/babel-plugin-transform-react/src/transforms/ClassAttributeTransform.js.html",
    "@twist/babel-plugin-transform-react/src/transforms/ClassAttributeTransform.js",
    "file"
  ],
  [
    "@twist/babel-plugin-transform-react/src/transforms/constructorpropstransform.js",
    "file/@twist/babel-plugin-transform-react/src/transforms/ConstructorPropsTransform.js.html",
    "@twist/babel-plugin-transform-react/src/transforms/ConstructorPropsTransform.js",
    "file"
  ],
  [
    "@twist/babel-plugin-transform-react/src/transforms/controlflowtransform.js",
    "file/@twist/babel-plugin-transform-react/src/transforms/ControlFlowTransform.js.html",
    "@twist/babel-plugin-transform-react/src/transforms/ControlFlowTransform.js",
    "file"
  ],
  [
    "@twist/babel-plugin-transform-react/src/transforms/namedchildrentransform.js",
    "file/@twist/babel-plugin-transform-react/src/transforms/NamedChildrenTransform.js.html",
    "@twist/babel-plugin-transform-react/src/transforms/NamedChildrenTransform.js",
    "file"
  ],
  [
    "@twist/babel-plugin-transform-react/src/transforms/refattributetransform.js",
    "file/@twist/babel-plugin-transform-react/src/transforms/RefAttributeTransform.js.html",
    "@twist/babel-plugin-transform-react/src/transforms/RefAttributeTransform.js",
    "file"
  ],
  [
    "@twist/babel-plugin-transform-react/src/transforms/styleattributetransform.js",
    "file/@twist/babel-plugin-transform-react/src/transforms/StyleAttributeTransform.js.html",
    "@twist/babel-plugin-transform-react/src/transforms/StyleAttributeTransform.js",
    "file"
  ],
  [
    "@twist/babel-plugin-transform/src/pathutils.js",
    "file/@twist/babel-plugin-transform/src/PathUtils.js.html",
    "@twist/babel-plugin-transform/src/PathUtils.js",
    "file"
  ],
  [
    "@twist/babel-plugin-transform/src/transformer.js",
    "file/@twist/babel-plugin-transform/src/Transformer.js.html",
    "@twist/babel-plugin-transform/src/Transformer.js",
    "file"
  ],
  [
    "@twist/babel-plugin-transform/src/camelcasehyphens.js",
    "file/@twist/babel-plugin-transform/src/camelCaseHyphens.js.html",
    "@twist/babel-plugin-transform/src/camelCaseHyphens.js",
    "file"
  ],
  [
    "@twist/babel-plugin-transform/src/index.js",
    "file/@twist/babel-plugin-transform/src/index.js.html",
    "@twist/babel-plugin-transform/src/index.js",
    "file"
  ],
  [
    "@twist/babel-plugin-transform/src/transforms/componentimporttransform.js",
    "file/@twist/babel-plugin-transform/src/transforms/ComponentImportTransform.js.html",
    "@twist/babel-plugin-transform/src/transforms/ComponentImportTransform.js",
    "file"
  ],
  [
    "@twist/babel-plugin-transform/src/transforms/decoratorimporttransform.js",
    "file/@twist/babel-plugin-transform/src/transforms/DecoratorImportTransform.js.html",
    "@twist/babel-plugin-transform/src/transforms/DecoratorImportTransform.js",
    "file"
  ],
  [
    "@twist/babel-plugin-transform/src/transforms/decoratorimporttransform.js~decoratordefinition",
    "typedef/index.html#static-typedef-DecoratorDefinition",
    "@twist/babel-plugin-transform/src/transforms/DecoratorImportTransform.js~DecoratorDefinition",
    "typedef"
  ],
  [
    "@twist/configuration/src/twistconfiguration.js",
    "file/@twist/configuration/src/TwistConfiguration.js.html",
    "@twist/configuration/src/TwistConfiguration.js",
    "file"
  ],
  [
    "@twist/core/index.js",
    "file/@twist/core/index.js.html",
    "@twist/core/index.js",
    "file"
  ],
  [
    "@twist/core/karma.conf.js",
    "file/@twist/core/karma.conf.js.html",
    "@twist/core/karma.conf.js",
    "file"
  ],
  [
    "@twist/core/src/basestore.jsx",
    "file/@twist/core/src/BaseStore.jsx.html",
    "@twist/core/src/BaseStore.jsx",
    "file"
  ],
  [
    "@twist/core/src/basestore.jsx~basestore#constructor",
    "class/@twist/core/src/BaseStore.jsx~BaseStore.html#instance-constructor-constructor",
    "@twist/core/src/BaseStore.jsx~BaseStore#constructor",
    "method"
  ],
  [
    "@twist/core/src/basestore.jsx~basestore#dispatch",
    "class/@twist/core/src/BaseStore.jsx~BaseStore.html#instance-method-dispatch",
    "@twist/core/src/BaseStore.jsx~BaseStore#dispatch",
    "method"
  ],
  [
    "@twist/core/src/basestore.jsx~basestore#getparentstore",
    "class/@twist/core/src/BaseStore.jsx~BaseStore.html#instance-method-getParentStore",
    "@twist/core/src/BaseStore.jsx~BaseStore#getParentStore",
    "method"
  ],
  [
    "@twist/core/src/binder.jsx",
    "file/@twist/core/src/Binder.jsx.html",
    "@twist/core/src/Binder.jsx",
    "file"
  ],
  [
    "@twist/core/src/binder.jsx~binder#apply",
    "class/@twist/core/src/Binder.jsx~Binder.html#instance-method-apply",
    "@twist/core/src/Binder.jsx~Binder#apply",
    "method"
  ],
  [
    "@twist/core/src/binder.jsx~binder#bindings",
    "class/@twist/core/src/Binder.jsx~Binder.html#instance-member-bindings",
    "@twist/core/src/Binder.jsx~Binder#bindings",
    "member"
  ],
  [
    "@twist/core/src/binder.jsx~binder#callback",
    "class/@twist/core/src/Binder.jsx~Binder.html#instance-member-callback",
    "@twist/core/src/Binder.jsx~Binder#callback",
    "member"
  ],
  [
    "@twist/core/src/binder.jsx~binder#compute",
    "class/@twist/core/src/Binder.jsx~Binder.html#instance-method-compute",
    "@twist/core/src/Binder.jsx~Binder#compute",
    "method"
  ],
  [
    "@twist/core/src/binder.jsx~binder#constructor",
    "class/@twist/core/src/Binder.jsx~Binder.html#instance-constructor-constructor",
    "@twist/core/src/Binder.jsx~Binder#constructor",
    "method"
  ],
  [
    "@twist/core/src/binder.jsx~binder#dirty",
    "class/@twist/core/src/Binder.jsx~Binder.html#instance-member-dirty",
    "@twist/core/src/Binder.jsx~Binder#dirty",
    "member"
  ],
  [
    "@twist/core/src/binder.jsx~binder#disposableparent",
    "class/@twist/core/src/Binder.jsx~Binder.html#instance-member-disposableParent",
    "@twist/core/src/Binder.jsx~Binder#disposableParent",
    "member"
  ],
  [
    "@twist/core/src/binder.jsx~binder#dispose",
    "class/@twist/core/src/Binder.jsx~Binder.html#instance-method-dispose",
    "@twist/core/src/Binder.jsx~Binder#dispose",
    "method"
  ],
  [
    "@twist/core/src/binder.jsx~binder#get",
    "class/@twist/core/src/Binder.jsx~Binder.html#instance-method-get",
    "@twist/core/src/Binder.jsx~Binder#get",
    "method"
  ],
  [
    "@twist/core/src/binder.jsx~binder#invalidate",
    "class/@twist/core/src/Binder.jsx~Binder.html#instance-member-invalidate",
    "@twist/core/src/Binder.jsx~Binder#invalidate",
    "member"
  ],
  [
    "@twist/core/src/binder.jsx~binder#previousvalue",
    "class/@twist/core/src/Binder.jsx~Binder.html#instance-member-previousValue",
    "@twist/core/src/Binder.jsx~Binder#previousValue",
    "member"
  ],
  [
    "@twist/core/src/binder.jsx~binder#removebindings",
    "class/@twist/core/src/Binder.jsx~Binder.html#instance-method-removeBindings",
    "@twist/core/src/Binder.jsx~Binder#removeBindings",
    "method"
  ],
  [
    "@twist/core/src/binder.jsx~binder#set",
    "class/@twist/core/src/Binder.jsx~Binder.html#instance-member-set",
    "@twist/core/src/Binder.jsx~Binder#set",
    "member"
  ],
  [
    "@twist/core/src/binder.jsx~binder#update",
    "class/@twist/core/src/Binder.jsx~Binder.html#instance-method-update",
    "@twist/core/src/Binder.jsx~Binder#update",
    "method"
  ],
  [
    "@twist/core/src/binder.jsx~binder#valuegetter",
    "class/@twist/core/src/Binder.jsx~Binder.html#instance-member-valueGetter",
    "@twist/core/src/Binder.jsx~Binder#valueGetter",
    "member"
  ],
  [
    "@twist/core/src/binder.jsx~binder.active",
    "class/@twist/core/src/Binder.jsx~Binder.html#static-member-active",
    "@twist/core/src/Binder.jsx~Binder.active",
    "member"
  ],
  [
    "@twist/core/src/binder.jsx~binder.mutator",
    "class/@twist/core/src/Binder.jsx~Binder.html#static-member-mutator",
    "@twist/core/src/Binder.jsx~Binder.mutator",
    "member"
  ],
  [
    "@twist/core/src/binder.jsx~binder.mutatorsstack",
    "class/@twist/core/src/Binder.jsx~Binder.html#static-member-mutatorsStack",
    "@twist/core/src/Binder.jsx~Binder.mutatorsStack",
    "member"
  ],
  [
    "@twist/core/src/binder.jsx~binder.popmutator",
    "class/@twist/core/src/Binder.jsx~Binder.html#static-method-popMutator",
    "@twist/core/src/Binder.jsx~Binder.popMutator",
    "method"
  ],
  [
    "@twist/core/src/binder.jsx~binder.pushmutator",
    "class/@twist/core/src/Binder.jsx~Binder.html#static-method-pushMutator",
    "@twist/core/src/Binder.jsx~Binder.pushMutator",
    "method"
  ],
  [
    "@twist/core/src/binder.jsx~binder.recordchange",
    "class/@twist/core/src/Binder.jsx~Binder.html#static-method-recordChange",
    "@twist/core/src/Binder.jsx~Binder.recordChange",
    "method"
  ],
  [
    "@twist/core/src/binder.jsx~binder.recordevent",
    "class/@twist/core/src/Binder.jsx~Binder.html#static-method-recordEvent",
    "@twist/core/src/Binder.jsx~Binder.recordEvent",
    "method"
  ],
  [
    "@twist/core/src/binder.jsx~binder.run",
    "class/@twist/core/src/Binder.jsx~Binder.html#static-method-run",
    "@twist/core/src/Binder.jsx~Binder.run",
    "method"
  ],
  [
    "@twist/core/src/collectionbinder.jsx",
    "file/@twist/core/src/CollectionBinder.jsx.html",
    "@twist/core/src/CollectionBinder.jsx",
    "file"
  ],
  [
    "@twist/core/src/collectionbinder.jsx~collectionbinder#invokecallback",
    "class/@twist/core/src/CollectionBinder.jsx~CollectionBinder.html#instance-method-invokeCallback",
    "@twist/core/src/CollectionBinder.jsx~CollectionBinder#invokeCallback",
    "method"
  ],
  [
    "@twist/core/src/collectionbinder.jsx~collectionbinder#lengthchanged",
    "class/@twist/core/src/CollectionBinder.jsx~CollectionBinder.html#instance-member-lengthChanged",
    "@twist/core/src/CollectionBinder.jsx~CollectionBinder#lengthChanged",
    "member"
  ],
  [
    "@twist/core/src/collectionbinder.jsx~collectionbinder#onlengthchanged",
    "class/@twist/core/src/CollectionBinder.jsx~CollectionBinder.html#instance-method-onLengthChanged",
    "@twist/core/src/CollectionBinder.jsx~CollectionBinder#onLengthChanged",
    "method"
  ],
  [
    "@twist/core/src/collectionbinder.jsx~collectionbinder#previousvalue",
    "class/@twist/core/src/CollectionBinder.jsx~CollectionBinder.html#instance-member-previousValue",
    "@twist/core/src/CollectionBinder.jsx~CollectionBinder#previousValue",
    "member"
  ],
  [
    "@twist/core/src/collectionbinder.jsx~collectionbinder#update",
    "class/@twist/core/src/CollectionBinder.jsx~CollectionBinder.html#instance-method-update",
    "@twist/core/src/CollectionBinder.jsx~CollectionBinder#update",
    "method"
  ],
  [
    "@twist/core/src/disposable.jsx",
    "file/@twist/core/src/Disposable.jsx.html",
    "@twist/core/src/Disposable.jsx",
    "file"
  ],
  [
    "@twist/core/src/disposable.jsx~disposable#[_disposables]",
    "class/@twist/core/src/Disposable.jsx~Disposable.html#instance-member-[_disposables]",
    "@twist/core/src/Disposable.jsx~Disposable#[_disposables]",
    "member"
  ],
  [
    "@twist/core/src/disposable.jsx~disposable#[_isdisposed]",
    "class/@twist/core/src/Disposable.jsx~Disposable.html#instance-member-[_isDisposed]",
    "@twist/core/src/Disposable.jsx~Disposable#[_isDisposed]",
    "member"
  ],
  [
    "@twist/core/src/disposable.jsx~disposable#dispose",
    "class/@twist/core/src/Disposable.jsx~Disposable.html#instance-method-dispose",
    "@twist/core/src/Disposable.jsx~Disposable#dispose",
    "method"
  ],
  [
    "@twist/core/src/disposable.jsx~disposable#disposelink",
    "class/@twist/core/src/Disposable.jsx~Disposable.html#instance-method-disposeLink",
    "@twist/core/src/Disposable.jsx~Disposable#disposeLink",
    "method"
  ],
  [
    "@twist/core/src/disposable.jsx~disposable#isdisposed",
    "class/@twist/core/src/Disposable.jsx~Disposable.html#instance-get-isDisposed",
    "@twist/core/src/Disposable.jsx~Disposable#isDisposed",
    "member"
  ],
  [
    "@twist/core/src/disposable.jsx~disposable#link",
    "class/@twist/core/src/Disposable.jsx~Disposable.html#instance-method-link",
    "@twist/core/src/Disposable.jsx~Disposable#link",
    "method"
  ],
  [
    "@twist/core/src/disposable.jsx~disposable#unlink",
    "class/@twist/core/src/Disposable.jsx~Disposable.html#instance-method-unlink",
    "@twist/core/src/Disposable.jsx~Disposable#unlink",
    "method"
  ],
  [
    "@twist/core/src/objectid.jsx",
    "file/@twist/core/src/ObjectId.jsx.html",
    "@twist/core/src/ObjectId.jsx",
    "file"
  ],
  [
    "@twist/core/src/objectid.jsx~objectid.get",
    "class/@twist/core/src/ObjectId.jsx~ObjectId.html#static-method-get",
    "@twist/core/src/ObjectId.jsx~ObjectId.get",
    "method"
  ],
  [
    "@twist/core/src/objectid.jsx~objectid.set",
    "class/@twist/core/src/ObjectId.jsx~ObjectId.html#static-method-set",
    "@twist/core/src/ObjectId.jsx~ObjectId.set",
    "method"
  ],
  [
    "@twist/core/src/observablearray.jsx",
    "file/@twist/core/src/ObservableArray.jsx.html",
    "@twist/core/src/ObservableArray.jsx",
    "file"
  ],
  [
    "@twist/core/src/observablearray.jsx~observablearray#at",
    "class/@twist/core/src/ObservableArray.jsx~ObservableArray.html#instance-method-at",
    "@twist/core/src/ObservableArray.jsx~ObservableArray#at",
    "method"
  ],
  [
    "@twist/core/src/observablearray.jsx~observablearray#base",
    "class/@twist/core/src/ObservableArray.jsx~ObservableArray.html#instance-member-base",
    "@twist/core/src/ObservableArray.jsx~ObservableArray#base",
    "member"
  ],
  [
    "@twist/core/src/observablearray.jsx~observablearray#concat",
    "class/@twist/core/src/ObservableArray.jsx~ObservableArray.html#instance-method-concat",
    "@twist/core/src/ObservableArray.jsx~ObservableArray#concat",
    "method"
  ],
  [
    "@twist/core/src/observablearray.jsx~observablearray#concattoarray",
    "class/@twist/core/src/ObservableArray.jsx~ObservableArray.html#instance-method-concatToArray",
    "@twist/core/src/ObservableArray.jsx~ObservableArray#concatToArray",
    "method"
  ],
  [
    "@twist/core/src/observablearray.jsx~observablearray#constructor",
    "class/@twist/core/src/ObservableArray.jsx~ObservableArray.html#instance-constructor-constructor",
    "@twist/core/src/ObservableArray.jsx~ObservableArray#constructor",
    "method"
  ],
  [
    "@twist/core/src/observablearray.jsx~observablearray#filtertoarray",
    "class/@twist/core/src/ObservableArray.jsx~ObservableArray.html#instance-method-filterToArray",
    "@twist/core/src/ObservableArray.jsx~ObservableArray#filterToArray",
    "method"
  ],
  [
    "@twist/core/src/observablearray.jsx~observablearray#length",
    "class/@twist/core/src/ObservableArray.jsx~ObservableArray.html#instance-set-length",
    "@twist/core/src/ObservableArray.jsx~ObservableArray#length",
    "member"
  ],
  [
    "@twist/core/src/observablearray.jsx~observablearray#length",
    "class/@twist/core/src/ObservableArray.jsx~ObservableArray.html#instance-get-length",
    "@twist/core/src/ObservableArray.jsx~ObservableArray#length",
    "member"
  ],
  [
    "@twist/core/src/observablearray.jsx~observablearray#maptoarray",
    "class/@twist/core/src/ObservableArray.jsx~ObservableArray.html#instance-method-mapToArray",
    "@twist/core/src/ObservableArray.jsx~ObservableArray#mapToArray",
    "method"
  ],
  [
    "@twist/core/src/observablearray.jsx~observablearray#removeitem",
    "class/@twist/core/src/ObservableArray.jsx~ObservableArray.html#instance-method-removeItem",
    "@twist/core/src/ObservableArray.jsx~ObservableArray#removeItem",
    "method"
  ],
  [
    "@twist/core/src/observablearray.jsx~observablearray#setat",
    "class/@twist/core/src/ObservableArray.jsx~ObservableArray.html#instance-method-setAt",
    "@twist/core/src/ObservableArray.jsx~ObservableArray#setAt",
    "method"
  ],
  [
    "@twist/core/src/observablearray.jsx~observablearray#slicetoarray",
    "class/@twist/core/src/ObservableArray.jsx~ObservableArray.html#instance-method-sliceToArray",
    "@twist/core/src/ObservableArray.jsx~ObservableArray#sliceToArray",
    "method"
  ],
  [
    "@twist/core/src/observablearray.jsx~observablearray#splicetoarray",
    "class/@twist/core/src/ObservableArray.jsx~ObservableArray.html#instance-method-spliceToArray",
    "@twist/core/src/ObservableArray.jsx~ObservableArray#spliceToArray",
    "method"
  ],
  [
    "@twist/core/src/observablearray.jsx~observablearray#swapitems",
    "class/@twist/core/src/ObservableArray.jsx~ObservableArray.html#instance-method-swapItems",
    "@twist/core/src/ObservableArray.jsx~ObservableArray#swapItems",
    "method"
  ],
  [
    "@twist/core/src/observablearray.jsx~observablearray#toarray",
    "class/@twist/core/src/ObservableArray.jsx~ObservableArray.html#instance-method-toArray",
    "@twist/core/src/ObservableArray.jsx~ObservableArray#toArray",
    "method"
  ],
  [
    "@twist/core/src/observablemap.jsx",
    "file/@twist/core/src/ObservableMap.jsx.html",
    "@twist/core/src/ObservableMap.jsx",
    "file"
  ],
  [
    "@twist/core/src/observablemap.jsx~observablemap#base",
    "class/@twist/core/src/ObservableMap.jsx~ObservableMap.html#instance-member-base",
    "@twist/core/src/ObservableMap.jsx~ObservableMap#base",
    "member"
  ],
  [
    "@twist/core/src/observablemap.jsx~observablemap#clear",
    "class/@twist/core/src/ObservableMap.jsx~ObservableMap.html#instance-method-clear",
    "@twist/core/src/ObservableMap.jsx~ObservableMap#clear",
    "method"
  ],
  [
    "@twist/core/src/observablemap.jsx~observablemap#constructor",
    "class/@twist/core/src/ObservableMap.jsx~ObservableMap.html#instance-constructor-constructor",
    "@twist/core/src/ObservableMap.jsx~ObservableMap#constructor",
    "method"
  ],
  [
    "@twist/core/src/observablemap.jsx~observablemap#delete",
    "class/@twist/core/src/ObservableMap.jsx~ObservableMap.html#instance-method-delete",
    "@twist/core/src/ObservableMap.jsx~ObservableMap#delete",
    "method"
  ],
  [
    "@twist/core/src/observablemap.jsx~observablemap#get",
    "class/@twist/core/src/ObservableMap.jsx~ObservableMap.html#instance-method-get",
    "@twist/core/src/ObservableMap.jsx~ObservableMap#get",
    "method"
  ],
  [
    "@twist/core/src/observablemap.jsx~observablemap#has",
    "class/@twist/core/src/ObservableMap.jsx~ObservableMap.html#instance-method-has",
    "@twist/core/src/ObservableMap.jsx~ObservableMap#has",
    "method"
  ],
  [
    "@twist/core/src/observablemap.jsx~observablemap#length",
    "class/@twist/core/src/ObservableMap.jsx~ObservableMap.html#instance-get-length",
    "@twist/core/src/ObservableMap.jsx~ObservableMap#length",
    "member"
  ],
  [
    "@twist/core/src/observablemap.jsx~observablemap#set",
    "class/@twist/core/src/ObservableMap.jsx~ObservableMap.html#instance-method-set",
    "@twist/core/src/ObservableMap.jsx~ObservableMap#set",
    "method"
  ],
  [
    "@twist/core/src/observablemap.jsx~observablemap#size",
    "class/@twist/core/src/ObservableMap.jsx~ObservableMap.html#instance-get-size",
    "@twist/core/src/ObservableMap.jsx~ObservableMap#size",
    "member"
  ],
  [
    "@twist/core/src/observablemap.jsx~observablemap#swapitems",
    "class/@twist/core/src/ObservableMap.jsx~ObservableMap.html#instance-method-swapItems",
    "@twist/core/src/ObservableMap.jsx~ObservableMap#swapItems",
    "method"
  ],
  [
    "@twist/core/src/observableset.jsx",
    "file/@twist/core/src/ObservableSet.jsx.html",
    "@twist/core/src/ObservableSet.jsx",
    "file"
  ],
  [
    "@twist/core/src/observableset.jsx~observableset#base",
    "class/@twist/core/src/ObservableSet.jsx~ObservableSet.html#instance-member-base",
    "@twist/core/src/ObservableSet.jsx~ObservableSet#base",
    "member"
  ],
  [
    "@twist/core/src/observableset.jsx~observableset#constructor",
    "class/@twist/core/src/ObservableSet.jsx~ObservableSet.html#instance-constructor-constructor",
    "@twist/core/src/ObservableSet.jsx~ObservableSet#constructor",
    "method"
  ],
  [
    "@twist/core/src/observableset.jsx~observableset#length",
    "class/@twist/core/src/ObservableSet.jsx~ObservableSet.html#instance-get-length",
    "@twist/core/src/ObservableSet.jsx~ObservableSet#length",
    "member"
  ],
  [
    "@twist/core/src/observableset.jsx~observableset#size",
    "class/@twist/core/src/ObservableSet.jsx~ObservableSet.html#instance-get-size",
    "@twist/core/src/ObservableSet.jsx~ObservableSet#size",
    "member"
  ],
  [
    "@twist/core/src/observableset.jsx~observableset#swapitems",
    "class/@twist/core/src/ObservableSet.jsx~ObservableSet.html#instance-method-swapItems",
    "@twist/core/src/ObservableSet.jsx~ObservableSet#swapItems",
    "method"
  ],
  [
    "@twist/core/src/scope.jsx",
    "file/@twist/core/src/Scope.jsx.html",
    "@twist/core/src/Scope.jsx",
    "file"
  ],
  [
    "@twist/core/src/scope.jsx~scope#clean",
    "class/@twist/core/src/Scope.jsx~Scope.html#instance-method-clean",
    "@twist/core/src/Scope.jsx~Scope#clean",
    "method"
  ],
  [
    "@twist/core/src/scope.jsx~scope#fork",
    "class/@twist/core/src/Scope.jsx~Scope.html#instance-method-fork",
    "@twist/core/src/Scope.jsx~Scope#fork",
    "method"
  ],
  [
    "@twist/core/src/signal.jsx",
    "file/@twist/core/src/Signal.jsx.html",
    "@twist/core/src/Signal.jsx",
    "file"
  ],
  [
    "@twist/core/src/signal.jsx~signal#[_owner]",
    "class/@twist/core/src/Signal.jsx~Signal.html#instance-member-[_owner]",
    "@twist/core/src/Signal.jsx~Signal#[_owner]",
    "member"
  ],
  [
    "@twist/core/src/signal.jsx~signal#add",
    "class/@twist/core/src/Signal.jsx~Signal.html#instance-method-add",
    "@twist/core/src/Signal.jsx~Signal#add",
    "method"
  ],
  [
    "@twist/core/src/signal.jsx~signal#constructor",
    "class/@twist/core/src/Signal.jsx~Signal.html#instance-constructor-constructor",
    "@twist/core/src/Signal.jsx~Signal#constructor",
    "method"
  ],
  [
    "@twist/core/src/signal.jsx~signal#handlers",
    "class/@twist/core/src/Signal.jsx~Signal.html#instance-member-handlers",
    "@twist/core/src/Signal.jsx~Signal#handlers",
    "member"
  ],
  [
    "@twist/core/src/signal.jsx~signal#remove",
    "class/@twist/core/src/Signal.jsx~Signal.html#instance-method-remove",
    "@twist/core/src/Signal.jsx~Signal#remove",
    "method"
  ],
  [
    "@twist/core/src/signal.jsx~signal#trigger",
    "class/@twist/core/src/Signal.jsx~Signal.html#instance-method-trigger",
    "@twist/core/src/Signal.jsx~Signal#trigger",
    "method"
  ],
  [
    "@twist/core/src/signal.jsx~signal#triggernoargs",
    "class/@twist/core/src/Signal.jsx~Signal.html#instance-method-triggerNoArgs",
    "@twist/core/src/Signal.jsx~Signal#triggerNoArgs",
    "method"
  ],
  [
    "@twist/core/src/signal.jsx~signal#triggerwitharray",
    "class/@twist/core/src/Signal.jsx~Signal.html#instance-method-triggerWithArray",
    "@twist/core/src/Signal.jsx~Signal#triggerWithArray",
    "method"
  ],
  [
    "@twist/core/src/signal.jsx~signal.listento",
    "class/@twist/core/src/Signal.jsx~Signal.html#static-method-listenTo",
    "@twist/core/src/Signal.jsx~Signal.listenTo",
    "method"
  ],
  [
    "@twist/core/src/signal.jsx~signal.off",
    "class/@twist/core/src/Signal.jsx~Signal.html#static-method-off",
    "@twist/core/src/Signal.jsx~Signal.off",
    "method"
  ],
  [
    "@twist/core/src/signal.jsx~signal.on",
    "class/@twist/core/src/Signal.jsx~Signal.html#static-method-on",
    "@twist/core/src/Signal.jsx~Signal.on",
    "method"
  ],
  [
    "@twist/core/src/signal.jsx~signal.stoplistening",
    "class/@twist/core/src/Signal.jsx~Signal.html#static-method-stopListening",
    "@twist/core/src/Signal.jsx~Signal.stopListening",
    "method"
  ],
  [
    "@twist/core/src/signal.jsx~signal.trigger",
    "class/@twist/core/src/Signal.jsx~Signal.html#static-method-trigger",
    "@twist/core/src/Signal.jsx~Signal.trigger",
    "method"
  ],
  [
    "@twist/core/src/signal.jsx~signal.triggernoargs",
    "class/@twist/core/src/Signal.jsx~Signal.html#static-method-triggerNoArgs",
    "@twist/core/src/Signal.jsx~Signal.triggerNoArgs",
    "method"
  ],
  [
    "@twist/core/src/signaldispatcher.jsx",
    "file/@twist/core/src/SignalDispatcher.jsx.html",
    "@twist/core/src/SignalDispatcher.jsx",
    "file"
  ],
  [
    "@twist/core/src/signaldispatcher.jsx~signaldispatcher#[hiddenkey]",
    "class/@twist/core/src/SignalDispatcher.jsx~SignalDispatcher.html#instance-member-[hiddenKey]",
    "@twist/core/src/SignalDispatcher.jsx~SignalDispatcher#[hiddenKey]",
    "member"
  ],
  [
    "@twist/core/src/signaldispatcher.jsx~signaldispatcher#[key]",
    "class/@twist/core/src/SignalDispatcher.jsx~SignalDispatcher.html#instance-member-[key]",
    "@twist/core/src/SignalDispatcher.jsx~SignalDispatcher#[key]",
    "member"
  ],
  [
    "@twist/core/src/signaldispatcher.jsx~signaldispatcher#defineobservable",
    "class/@twist/core/src/SignalDispatcher.jsx~SignalDispatcher.html#instance-method-defineObservable",
    "@twist/core/src/SignalDispatcher.jsx~SignalDispatcher#defineObservable",
    "method"
  ],
  [
    "@twist/core/src/signaldispatcher.jsx~signaldispatcher#dispose",
    "class/@twist/core/src/SignalDispatcher.jsx~SignalDispatcher.html#instance-method-dispose",
    "@twist/core/src/SignalDispatcher.jsx~SignalDispatcher#dispose",
    "method"
  ],
  [
    "@twist/core/src/signaldispatcher.jsx~signaldispatcher#listento",
    "class/@twist/core/src/SignalDispatcher.jsx~SignalDispatcher.html#instance-method-listenTo",
    "@twist/core/src/SignalDispatcher.jsx~SignalDispatcher#listenTo",
    "method"
  ],
  [
    "@twist/core/src/signaldispatcher.jsx~signaldispatcher#off",
    "class/@twist/core/src/SignalDispatcher.jsx~SignalDispatcher.html#instance-method-off",
    "@twist/core/src/SignalDispatcher.jsx~SignalDispatcher#off",
    "method"
  ],
  [
    "@twist/core/src/signaldispatcher.jsx~signaldispatcher#on",
    "class/@twist/core/src/SignalDispatcher.jsx~SignalDispatcher.html#instance-method-on",
    "@twist/core/src/SignalDispatcher.jsx~SignalDispatcher#on",
    "method"
  ],
  [
    "@twist/core/src/signaldispatcher.jsx~signaldispatcher#stoplistening",
    "class/@twist/core/src/SignalDispatcher.jsx~SignalDispatcher.html#instance-method-stopListening",
    "@twist/core/src/SignalDispatcher.jsx~SignalDispatcher#stopListening",
    "method"
  ],
  [
    "@twist/core/src/signaldispatcher.jsx~signaldispatcher#trigger",
    "class/@twist/core/src/SignalDispatcher.jsx~SignalDispatcher.html#instance-method-trigger",
    "@twist/core/src/SignalDispatcher.jsx~SignalDispatcher#trigger",
    "method"
  ],
  [
    "@twist/core/src/signaldispatcher.jsx~signaldispatcher#watch",
    "class/@twist/core/src/SignalDispatcher.jsx~SignalDispatcher.html#instance-method-watch",
    "@twist/core/src/SignalDispatcher.jsx~SignalDispatcher#watch",
    "method"
  ],
  [
    "@twist/core/src/signaldispatcher.jsx~signaldispatcher#watchcollection",
    "class/@twist/core/src/SignalDispatcher.jsx~SignalDispatcher.html#instance-method-watchCollection",
    "@twist/core/src/SignalDispatcher.jsx~SignalDispatcher#watchCollection",
    "method"
  ],
  [
    "@twist/core/src/taskqueue.jsx",
    "file/@twist/core/src/TaskQueue.jsx.html",
    "@twist/core/src/TaskQueue.jsx",
    "file"
  ],
  [
    "@twist/core/src/decorators/abstract.jsx",
    "file/@twist/core/src/decorators/Abstract.jsx.html",
    "@twist/core/src/decorators/Abstract.jsx",
    "file"
  ],
  [
    "@twist/core/src/decorators/action.jsx",
    "file/@twist/core/src/decorators/Action.jsx.html",
    "@twist/core/src/decorators/Action.jsx",
    "file"
  ],
  [
    "@twist/core/src/decorators/bind.jsx",
    "file/@twist/core/src/decorators/Bind.jsx.html",
    "@twist/core/src/decorators/Bind.jsx",
    "file"
  ],
  [
    "@twist/core/src/decorators/cache.jsx",
    "file/@twist/core/src/decorators/Cache.jsx.html",
    "@twist/core/src/decorators/Cache.jsx",
    "file"
  ],
  [
    "@twist/core/src/decorators/debounce.jsx",
    "file/@twist/core/src/decorators/Debounce.jsx.html",
    "@twist/core/src/decorators/Debounce.jsx",
    "file"
  ],
  [
    "@twist/core/src/decorators/delay.jsx",
    "file/@twist/core/src/decorators/Delay.jsx.html",
    "@twist/core/src/decorators/Delay.jsx",
    "file"
  ],
  [
    "@twist/core/src/decorators/memoize.jsx",
    "file/@twist/core/src/decorators/Memoize.jsx.html",
    "@twist/core/src/decorators/Memoize.jsx",
    "file"
  ],
  [
    "@twist/core/src/decorators/observable.jsx",
    "file/@twist/core/src/decorators/Observable.jsx.html",
    "@twist/core/src/decorators/Observable.jsx",
    "file"
  ],
  [
    "@twist/core/src/decorators/prototype.jsx",
    "file/@twist/core/src/decorators/Prototype.jsx.html",
    "@twist/core/src/decorators/Prototype.jsx",
    "file"
  ],
  [
    "@twist/core/src/decorators/state.jsx",
    "file/@twist/core/src/decorators/State.jsx.html",
    "@twist/core/src/decorators/State.jsx",
    "file"
  ],
  [
    "@twist/core/src/decorators/state.jsx~state#alias",
    "class/@twist/core/src/decorators/State.jsx~State.html#instance-method-alias",
    "@twist/core/src/decorators/State.jsx~State#alias",
    "method"
  ],
  [
    "@twist/core/src/decorators/state.jsx~state#byarray",
    "class/@twist/core/src/decorators/State.jsx~State.html#instance-method-byArray",
    "@twist/core/src/decorators/State.jsx~State#byArray",
    "method"
  ],
  [
    "@twist/core/src/decorators/state.jsx~state#bybooleanval",
    "class/@twist/core/src/decorators/State.jsx~State.html#instance-method-byBooleanVal",
    "@twist/core/src/decorators/State.jsx~State#byBooleanVal",
    "method"
  ],
  [
    "@twist/core/src/decorators/state.jsx~state#bycustomref",
    "class/@twist/core/src/decorators/State.jsx~State.html#instance-method-byCustomRef",
    "@twist/core/src/decorators/State.jsx~State#byCustomRef",
    "method"
  ],
  [
    "@twist/core/src/decorators/state.jsx~state#bycustomrefarray",
    "class/@twist/core/src/decorators/State.jsx~State.html#instance-method-byCustomRefArray",
    "@twist/core/src/decorators/State.jsx~State#byCustomRefArray",
    "method"
  ],
  [
    "@twist/core/src/decorators/state.jsx~state#bycustomval",
    "class/@twist/core/src/decorators/State.jsx~State.html#instance-method-byCustomVal",
    "@twist/core/src/decorators/State.jsx~State#byCustomVal",
    "method"
  ],
  [
    "@twist/core/src/decorators/state.jsx~state#bymap",
    "class/@twist/core/src/decorators/State.jsx~State.html#instance-method-byMap",
    "@twist/core/src/decorators/State.jsx~State#byMap",
    "method"
  ],
  [
    "@twist/core/src/decorators/state.jsx~state#bynumberval",
    "class/@twist/core/src/decorators/State.jsx~State.html#instance-method-byNumberVal",
    "@twist/core/src/decorators/State.jsx~State#byNumberVal",
    "method"
  ],
  [
    "@twist/core/src/decorators/state.jsx~state#byoptionalref",
    "class/@twist/core/src/decorators/State.jsx~State.html#instance-method-byOptionalRef",
    "@twist/core/src/decorators/State.jsx~State#byOptionalRef",
    "method"
  ],
  [
    "@twist/core/src/decorators/state.jsx~state#byref",
    "class/@twist/core/src/decorators/State.jsx~State.html#instance-method-byRef",
    "@twist/core/src/decorators/State.jsx~State#byRef",
    "method"
  ],
  [
    "@twist/core/src/decorators/state.jsx~state#byrefarray",
    "class/@twist/core/src/decorators/State.jsx~State.html#instance-method-byRefArray",
    "@twist/core/src/decorators/State.jsx~State#byRefArray",
    "method"
  ],
  [
    "@twist/core/src/decorators/state.jsx~state#byrefmap",
    "class/@twist/core/src/decorators/State.jsx~State.html#instance-method-byRefMap",
    "@twist/core/src/decorators/State.jsx~State#byRefMap",
    "method"
  ],
  [
    "@twist/core/src/decorators/state.jsx~state#bysimpleval",
    "class/@twist/core/src/decorators/State.jsx~State.html#instance-method-bySimpleVal",
    "@twist/core/src/decorators/State.jsx~State#bySimpleVal",
    "method"
  ],
  [
    "@twist/core/src/decorators/state.jsx~state#byval",
    "class/@twist/core/src/decorators/State.jsx~State.html#instance-method-byVal",
    "@twist/core/src/decorators/State.jsx~State#byVal",
    "method"
  ],
  [
    "@twist/core/src/decorators/store.jsx",
    "file/@twist/core/src/decorators/Store.jsx.html",
    "@twist/core/src/decorators/Store.jsx",
    "file"
  ],
  [
    "@twist/core/src/decorators/task.jsx",
    "file/@twist/core/src/decorators/Task.jsx.html",
    "@twist/core/src/decorators/Task.jsx",
    "file"
  ],
  [
    "@twist/core/src/decorators/throttle.jsx",
    "file/@twist/core/src/decorators/Throttle.jsx.html",
    "@twist/core/src/decorators/Throttle.jsx",
    "file"
  ],
  [
    "@twist/core/src/decorators/wrap.jsx",
    "file/@twist/core/src/decorators/Wrap.jsx.html",
    "@twist/core/src/decorators/Wrap.jsx",
    "file"
  ],
  [
    "@twist/core/src/middleware/protectormiddleware.jsx",
    "file/@twist/core/src/middleware/protectorMiddleware.jsx.html",
    "@twist/core/src/middleware/protectorMiddleware.jsx",
    "file"
  ],
  [
    "@twist/core/src/middleware/remotedevmiddleware.jsx",
    "file/@twist/core/src/middleware/remoteDevMiddleware.jsx.html",
    "@twist/core/src/middleware/remoteDevMiddleware.jsx",
    "file"
  ],
  [
    "@twist/core/src/middleware/thunkmiddleware.jsx",
    "file/@twist/core/src/middleware/thunkMiddleware.jsx.html",
    "@twist/core/src/middleware/thunkMiddleware.jsx",
    "file"
  ],
  [
    "@twist/core/test/bindertest.jsx",
    "test-file/@twist/core/test/BinderTest.jsx.html",
    "@twist/core/test/BinderTest.jsx",
    "testFile"
  ],
  [
    "@twist/core/test/collectionbindertest.jsx",
    "test-file/@twist/core/test/CollectionBinderTest.jsx.html",
    "@twist/core/test/CollectionBinderTest.jsx",
    "testFile"
  ],
  [
    "@twist/core/test/disposabletest.jsx",
    "test-file/@twist/core/test/DisposableTest.jsx.html",
    "@twist/core/test/DisposableTest.jsx",
    "testFile"
  ],
  [
    "@twist/core/test/observablearraytest.jsx",
    "test-file/@twist/core/test/ObservableArrayTest.jsx.html",
    "@twist/core/test/ObservableArrayTest.jsx",
    "testFile"
  ],
  [
    "@twist/core/test/observablemaptest.jsx",
    "test-file/@twist/core/test/ObservableMapTest.jsx.html",
    "@twist/core/test/ObservableMapTest.jsx",
    "testFile"
  ],
  [
    "@twist/core/test/observablesettest.jsx",
    "test-file/@twist/core/test/ObservableSetTest.jsx.html",
    "@twist/core/test/ObservableSetTest.jsx",
    "testFile"
  ],
  [
    "@twist/core/test/scopetest.jsx",
    "test-file/@twist/core/test/ScopeTest.jsx.html",
    "@twist/core/test/ScopeTest.jsx",
    "testFile"
  ],
  [
    "@twist/core/test/signaldispatchertest.jsx",
    "test-file/@twist/core/test/SignalDispatcherTest.jsx.html",
    "@twist/core/test/SignalDispatcherTest.jsx",
    "testFile"
  ],
  [
    "@twist/core/test/signaltest.jsx",
    "test-file/@twist/core/test/SignalTest.jsx.html",
    "@twist/core/test/SignalTest.jsx",
    "testFile"
  ],
  [
    "@twist/core/test/decorators/abstracttest.jsx",
    "test-file/@twist/core/test/decorators/AbstractTest.jsx.html",
    "@twist/core/test/decorators/AbstractTest.jsx",
    "testFile"
  ],
  [
    "@twist/core/test/decorators/actiontest.jsx",
    "test-file/@twist/core/test/decorators/ActionTest.jsx.html",
    "@twist/core/test/decorators/ActionTest.jsx",
    "testFile"
  ],
  [
    "@twist/core/test/decorators/bindtest.jsx",
    "test-file/@twist/core/test/decorators/BindTest.jsx.html",
    "@twist/core/test/decorators/BindTest.jsx",
    "testFile"
  ],
  [
    "@twist/core/test/decorators/cachetest.jsx",
    "test-file/@twist/core/test/decorators/CacheTest.jsx.html",
    "@twist/core/test/decorators/CacheTest.jsx",
    "testFile"
  ],
  [
    "@twist/core/test/decorators/debouncetest.jsx",
    "test-file/@twist/core/test/decorators/DebounceTest.jsx.html",
    "@twist/core/test/decorators/DebounceTest.jsx",
    "testFile"
  ],
  [
    "@twist/core/test/decorators/delaytest.jsx",
    "test-file/@twist/core/test/decorators/DelayTest.jsx.html",
    "@twist/core/test/decorators/DelayTest.jsx",
    "testFile"
  ],
  [
    "@twist/core/test/decorators/memoizetest.jsx",
    "test-file/@twist/core/test/decorators/MemoizeTest.jsx.html",
    "@twist/core/test/decorators/MemoizeTest.jsx",
    "testFile"
  ],
  [
    "@twist/core/test/decorators/mutablestoretest.jsx",
    "test-file/@twist/core/test/decorators/MutableStoreTest.jsx.html",
    "@twist/core/test/decorators/MutableStoreTest.jsx",
    "testFile"
  ],
  [
    "@twist/core/test/decorators/observabletest.jsx",
    "test-file/@twist/core/test/decorators/ObservableTest.jsx.html",
    "@twist/core/test/decorators/ObservableTest.jsx",
    "testFile"
  ],
  [
    "@twist/core/test/decorators/prototypetest.jsx",
    "test-file/@twist/core/test/decorators/PrototypeTest.jsx.html",
    "@twist/core/test/decorators/PrototypeTest.jsx",
    "testFile"
  ],
  [
    "@twist/core/test/decorators/statetest.jsx",
    "test-file/@twist/core/test/decorators/StateTest.jsx.html",
    "@twist/core/test/decorators/StateTest.jsx",
    "testFile"
  ],
  [
    "@twist/core/test/decorators/storetest.jsx",
    "test-file/@twist/core/test/decorators/StoreTest.jsx.html",
    "@twist/core/test/decorators/StoreTest.jsx",
    "testFile"
  ],
  [
    "@twist/core/test/decorators/tasktest.jsx",
    "test-file/@twist/core/test/decorators/TaskTest.jsx.html",
    "@twist/core/test/decorators/TaskTest.jsx",
    "testFile"
  ],
  [
    "@twist/core/test/decorators/throttletest.jsx",
    "test-file/@twist/core/test/decorators/ThrottleTest.jsx.html",
    "@twist/core/test/decorators/ThrottleTest.jsx",
    "testFile"
  ],
  [
    "@twist/core/test/middleware/custommiddlewaretest.jsx",
    "test-file/@twist/core/test/middleware/CustomMiddlewareTest.jsx.html",
    "@twist/core/test/middleware/CustomMiddlewareTest.jsx",
    "testFile"
  ],
  [
    "@twist/core/test/middleware/protectormiddlewaretest.jsx",
    "test-file/@twist/core/test/middleware/ProtectorMiddlewareTest.jsx.html",
    "@twist/core/test/middleware/ProtectorMiddlewareTest.jsx",
    "testFile"
  ],
  [
    "@twist/core/test/middleware/remotedevmiddlewaretest.jsx",
    "test-file/@twist/core/test/middleware/RemoteDevMiddlewareTest.jsx.html",
    "@twist/core/test/middleware/RemoteDevMiddlewareTest.jsx",
    "testFile"
  ],
  [
    "@twist/core/test/middleware/thunkmiddlewaretest.jsx",
    "test-file/@twist/core/test/middleware/ThunkMiddlewareTest.jsx.html",
    "@twist/core/test/middleware/ThunkMiddlewareTest.jsx",
    "testFile"
  ],
  [
    "@twist/eslint-plugin-core/index.js",
    "file/@twist/eslint-plugin-core/index.js.html",
    "@twist/eslint-plugin-core/index.js",
    "file"
  ],
  [
    "@twist/eslint-plugin-core/src/rules/constructor-super.js",
    "file/@twist/eslint-plugin-core/src/rules/constructor-super.js.html",
    "@twist/eslint-plugin-core/src/rules/constructor-super.js",
    "file"
  ],
  [
    "@twist/eslint-plugin-core/src/rules/jsx-member-vars.js",
    "file/@twist/eslint-plugin-core/src/rules/jsx-member-vars.js.html",
    "@twist/eslint-plugin-core/src/rules/jsx-member-vars.js",
    "file"
  ],
  [
    "@twist/eslint-plugin-core/src/rules/no-undef.js",
    "file/@twist/eslint-plugin-core/src/rules/no-undef.js.html",
    "@twist/eslint-plugin-core/src/rules/no-undef.js",
    "file"
  ],
  [
    "@twist/eslint-plugin-core/src/twist-config.js",
    "file/@twist/eslint-plugin-core/src/twist-config.js.html",
    "@twist/eslint-plugin-core/src/twist-config.js",
    "file"
  ],
  [
    "@twist/react-webpack-plugin/src/reacttwistwebpackplugin.js",
    "file/@twist/react-webpack-plugin/src/ReactTwistWebpackPlugin.js.html",
    "@twist/react-webpack-plugin/src/ReactTwistWebpackPlugin.js",
    "file"
  ],
  [
    "@twist/react-webpack-plugin/src/convertruletocondition.js",
    "file/@twist/react-webpack-plugin/src/convertRuleToCondition.js.html",
    "@twist/react-webpack-plugin/src/convertRuleToCondition.js",
    "file"
  ],
  [
    "@twist/react/index.js",
    "file/@twist/react/index.js.html",
    "@twist/react/index.js",
    "file"
  ],
  [
    "@twist/react/karma.conf.js",
    "file/@twist/react/karma.conf.js.html",
    "@twist/react/karma.conf.js",
    "file"
  ],
  [
    "@twist/react/src/basecomponent.jsx",
    "file/@twist/react/src/BaseComponent.jsx.html",
    "@twist/react/src/BaseComponent.jsx",
    "file"
  ],
  [
    "@twist/react/src/basecomponent.jsx~component#[_newprops]",
    "class/@twist/react/src/BaseComponent.jsx~Component.html#instance-member-[_newProps]",
    "@twist/react/src/BaseComponent.jsx~Component#[_newProps]",
    "member"
  ],
  [
    "@twist/react/src/basecomponent.jsx~component#[_originalrender]",
    "class/@twist/react/src/BaseComponent.jsx~Component.html#instance-member-[_originalRender]",
    "@twist/react/src/BaseComponent.jsx~Component#[_originalRender]",
    "member"
  ],
  [
    "@twist/react/src/basecomponent.jsx~component#[_props]",
    "class/@twist/react/src/BaseComponent.jsx~Component.html#instance-member-[_props]",
    "@twist/react/src/BaseComponent.jsx~Component#[_props]",
    "member"
  ],
  [
    "@twist/react/src/basecomponent.jsx~component#[_scope]",
    "class/@twist/react/src/BaseComponent.jsx~Component.html#instance-member-[_scope]",
    "@twist/react/src/BaseComponent.jsx~Component#[_scope]",
    "member"
  ],
  [
    "@twist/react/src/basecomponent.jsx~component#children",
    "class/@twist/react/src/BaseComponent.jsx~Component.html#instance-get-children",
    "@twist/react/src/BaseComponent.jsx~Component#children",
    "member"
  ],
  [
    "@twist/react/src/basecomponent.jsx~component#constructor",
    "class/@twist/react/src/BaseComponent.jsx~Component.html#instance-constructor-constructor",
    "@twist/react/src/BaseComponent.jsx~Component#constructor",
    "method"
  ],
  [
    "@twist/react/src/basecomponent.jsx~component#props",
    "class/@twist/react/src/BaseComponent.jsx~Component.html#instance-get-props",
    "@twist/react/src/BaseComponent.jsx~Component#props",
    "member"
  ],
  [
    "@twist/react/src/basecomponent.jsx~component#props",
    "class/@twist/react/src/BaseComponent.jsx~Component.html#instance-set-props",
    "@twist/react/src/BaseComponent.jsx~Component#props",
    "member"
  ],
  [
    "@twist/react/src/basecomponent.jsx~component#renderchildren",
    "class/@twist/react/src/BaseComponent.jsx~Component.html#instance-method-renderChildren",
    "@twist/react/src/BaseComponent.jsx~Component#renderChildren",
    "method"
  ],
  [
    "@twist/react/src/basecomponent.jsx~component#scope",
    "class/@twist/react/src/BaseComponent.jsx~Component.html#instance-get-scope",
    "@twist/react/src/BaseComponent.jsx~Component#scope",
    "member"
  ],
  [
    "@twist/react/src/basecomponent.jsx~component#trigger",
    "class/@twist/react/src/BaseComponent.jsx~Component.html#instance-method-trigger",
    "@twist/react/src/BaseComponent.jsx~Component#trigger",
    "method"
  ],
  [
    "@twist/react/src/basecomponent.jsx~component#undeclaredattributes",
    "class/@twist/react/src/BaseComponent.jsx~Component.html#instance-method-undeclaredAttributes",
    "@twist/react/src/BaseComponent.jsx~Component#undeclaredAttributes",
    "method"
  ],
  [
    "@twist/react/src/basevirtualcomponent.jsx",
    "file/@twist/react/src/BaseVirtualComponent.jsx.html",
    "@twist/react/src/BaseVirtualComponent.jsx",
    "file"
  ],
  [
    "@twist/react/src/basevirtualcomponent.jsx~basevirtualcomponent#[_dirty]",
    "class/@twist/react/src/BaseVirtualComponent.jsx~BaseVirtualComponent.html#instance-member-[_dirty]",
    "@twist/react/src/BaseVirtualComponent.jsx~BaseVirtualComponent#[_dirty]",
    "member"
  ],
  [
    "@twist/react/src/basevirtualcomponent.jsx~basevirtualcomponent#[_queuedupdate]",
    "class/@twist/react/src/BaseVirtualComponent.jsx~BaseVirtualComponent.html#instance-member-[_queuedUpdate]",
    "@twist/react/src/BaseVirtualComponent.jsx~BaseVirtualComponent#[_queuedUpdate]",
    "member"
  ],
  [
    "@twist/react/src/basevirtualcomponent.jsx~basevirtualcomponent#children",
    "class/@twist/react/src/BaseVirtualComponent.jsx~BaseVirtualComponent.html#instance-get-children",
    "@twist/react/src/BaseVirtualComponent.jsx~BaseVirtualComponent#children",
    "member"
  ],
  [
    "@twist/react/src/basevirtualcomponent.jsx~basevirtualcomponent#constructor",
    "class/@twist/react/src/BaseVirtualComponent.jsx~BaseVirtualComponent.html#instance-constructor-constructor",
    "@twist/react/src/BaseVirtualComponent.jsx~BaseVirtualComponent#constructor",
    "method"
  ],
  [
    "@twist/react/src/basevirtualcomponent.jsx~basevirtualcomponent#linktocomponent",
    "class/@twist/react/src/BaseVirtualComponent.jsx~BaseVirtualComponent.html#instance-method-linkToComponent",
    "@twist/react/src/BaseVirtualComponent.jsx~BaseVirtualComponent#linkToComponent",
    "method"
  ],
  [
    "@twist/react/src/basevirtualcomponent.jsx~basevirtualcomponent#render",
    "class/@twist/react/src/BaseVirtualComponent.jsx~BaseVirtualComponent.html#instance-method-render",
    "@twist/react/src/BaseVirtualComponent.jsx~BaseVirtualComponent#render",
    "method"
  ],
  [
    "@twist/react/src/basevirtualcomponent.jsx~basevirtualcomponent#renderchildren",
    "class/@twist/react/src/BaseVirtualComponent.jsx~BaseVirtualComponent.html#instance-method-renderChildren",
    "@twist/react/src/BaseVirtualComponent.jsx~BaseVirtualComponent#renderChildren",
    "method"
  ],
  [
    "@twist/react/src/decorators/attribute.jsx",
    "file/@twist/react/src/decorators/Attribute.jsx.html",
    "@twist/react/src/decorators/Attribute.jsx",
    "file"
  ],
  [
    "@twist/react/src/decorators/component.jsx",
    "file/@twist/react/src/decorators/Component.jsx.html",
    "@twist/react/src/decorators/Component.jsx",
    "file"
  ],
  [
    "",
    "test-file/@twist/core/test/BinderTest.jsx.html#lineNumber20",
    "Bindings.Binder",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/BinderTest.jsx.html#lineNumber269",
    "Bindings.Binder binder without callback should not crash",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/BinderTest.jsx.html#lineNumber199",
    "Bindings.Binder binding to a promise - constructed inside watch",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/BinderTest.jsx.html#lineNumber180",
    "Bindings.Binder binding to a promise - external to watch",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/BinderTest.jsx.html#lineNumber300",
    "Bindings.Binder can push and pop mutators",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/BinderTest.jsx.html#lineNumber284",
    "Bindings.Binder cannot pop with no mutators",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/BinderTest.jsx.html#lineNumber22",
    "Bindings.Binder detect property change - bind to function",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/BinderTest.jsx.html#lineNumber69",
    "Bindings.Binder detect property change - bind to getter/setter",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/BinderTest.jsx.html#lineNumber42",
    "Bindings.Binder detect property change - should not trigger if expression value unchanged",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/BinderTest.jsx.html#lineNumber96",
    "Bindings.Binder detect property change - without first run",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/BinderTest.jsx.html#lineNumber209",
    "Bindings.Binder mutation within a binder",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/BinderTest.jsx.html#lineNumber239",
    "Bindings.Binder mutation within a binder - no invalidate",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/BinderTest.jsx.html#lineNumber116",
    "Bindings.Binder previous bindings should be disposed when a value changes",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/BinderTest.jsx.html#lineNumber148",
    "Bindings.Binder previous bindings should be disposed when a value changes",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/CollectionBinderTest.jsx.html#lineNumber19",
    "Bindings.CollectionBinder",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/CollectionBinderTest.jsx.html#lineNumber21",
    "Bindings.CollectionBinder detect ObservableArray length change",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/CollectionBinderTest.jsx.html#lineNumber69",
    "Bindings.CollectionBinder detect ObservableMap length change",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/CollectionBinderTest.jsx.html#lineNumber40",
    "Bindings.CollectionBinder detect ObservableSet length change",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/SignalTest.jsx.html#lineNumber19",
    "Bindings.Signal",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/SignalTest.jsx.html#lineNumber45",
    "Bindings.Signal adding two events",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/SignalTest.jsx.html#lineNumber77",
    "Bindings.Signal events are not enumerable",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/SignalTest.jsx.html#lineNumber121",
    "Bindings.Signal listenTo",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/SignalTest.jsx.html#lineNumber34",
    "Bindings.Signal owner is respected",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/SignalTest.jsx.html#lineNumber58",
    "Bindings.Signal removing event name before signals were initialized",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/SignalTest.jsx.html#lineNumber66",
    "Bindings.Signal removing event name that doesn't exist",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/SignalTest.jsx.html#lineNumber137",
    "Bindings.Signal stopListening on empty object",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/SignalTest.jsx.html#lineNumber159",
    "Bindings.Signal stopListening with name and handler matching",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/SignalTest.jsx.html#lineNumber142",
    "Bindings.Signal stopListening with name matching",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/SignalTest.jsx.html#lineNumber176",
    "Bindings.Signal stopListening with no matching callback",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/SignalTest.jsx.html#lineNumber21",
    "Bindings.Signal trigger event",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/SignalTest.jsx.html#lineNumber91",
    "Bindings.Signal trigger event with arguments",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/SignalTest.jsx.html#lineNumber103",
    "Bindings.Signal trigger should have no effect after removing event handler",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/middleware/CustomMiddlewareTest.jsx.html#lineNumber18",
    "Custom Middleware",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/middleware/CustomMiddlewareTest.jsx.html#lineNumber20",
    "Custom Middleware Can supply custom middleware, to transform an action",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/middleware/RemoteDevMiddlewareTest.jsx.html#lineNumber69",
    "Devtools Middleware",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/middleware/RemoteDevMiddlewareTest.jsx.html#lineNumber84",
    "Devtools Middleware Enable devtools middleware - should connect and disconnect",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/middleware/RemoteDevMiddlewareTest.jsx.html#lineNumber71",
    "Devtools Middleware Enable devtools middleware - should give warning if devtools not installed",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/ScopeTest.jsx.html#lineNumber19",
    "JSX.Scope",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/ScopeTest.jsx.html#lineNumber48",
    "JSX.Scope should be able to clean a scope",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/ScopeTest.jsx.html#lineNumber28",
    "JSX.Scope should be able to create a nested scope",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/ScopeTest.jsx.html#lineNumber21",
    "JSX.Scope should be able to create a scope",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/decorators/ObservableTest.jsx.html#lineNumber19",
    "Observable Decorator",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/decorators/ObservableTest.jsx.html#lineNumber62",
    "Observable Decorator check for events",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/decorators/ObservableTest.jsx.html#lineNumber77",
    "Observable Decorator check for inherited classes events",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/decorators/ObservableTest.jsx.html#lineNumber21",
    "Observable Decorator default value",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/decorators/ObservableTest.jsx.html#lineNumber30",
    "Observable Decorator inherited default value",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/decorators/ObservableTest.jsx.html#lineNumber46",
    "Observable Decorator replace default value",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/decorators/ObservableTest.jsx.html#lineNumber142",
    "Observable Decorator should not invalidate binders if change a NaN to a NaN",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/decorators/ObservableTest.jsx.html#lineNumber96",
    "Observable Decorator triggers an update when changed asynchronously",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/middleware/ProtectorMiddlewareTest.jsx.html#lineNumber21",
    "Protector Middleware",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/middleware/ProtectorMiddlewareTest.jsx.html#lineNumber23",
    "Protector Middleware @Action cannot perform asynchronous operations (promises, timeout etc), when protector middleware is enabled",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/middleware/ProtectorMiddlewareTest.jsx.html#lineNumber67",
    "Protector Middleware Asynchronous @Action can perform asynchronous operations (promises, timeout etc), when protector middleware is enabled",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/middleware/ProtectorMiddlewareTest.jsx.html#lineNumber122",
    "Protector Middleware Asynchronous @Action in a nested store can perform asynchronous operations (promises, timeout etc), when protector middleware is enabled",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/decorators/MutableStoreTest.jsx.html#lineNumber45",
    "Tests",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/decorators/StoreTest.jsx.html#lineNumber47",
    "Tests",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/decorators/StoreTest.jsx.html#lineNumber71",
    "Tests Basic store - action must be a string",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/decorators/StoreTest.jsx.html#lineNumber49",
    "Tests Basic store - can import and export",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/decorators/StoreTest.jsx.html#lineNumber60",
    "Tests Basic store - can initialise from JSON, and dispatch unknown action",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/decorators/MutableStoreTest.jsx.html#lineNumber62",
    "Tests Can mutate @State.byRef",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/decorators/MutableStoreTest.jsx.html#lineNumber78",
    "Tests Can mutate @State.byRefArray",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/decorators/MutableStoreTest.jsx.html#lineNumber211",
    "Tests Can mutate @State.byRefMap",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/decorators/MutableStoreTest.jsx.html#lineNumber47",
    "Tests Can mutate @State.byVal",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/decorators/StoreTest.jsx.html#lineNumber837",
    "Tests Can't store the same store in more than one store",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/decorators/MutableStoreTest.jsx.html#lineNumber155",
    "Tests Modifying an array with @State.byRefArray preserves connection to parent store",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/decorators/MutableStoreTest.jsx.html#lineNumber245",
    "Tests Setting a store results in a copy",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/decorators/StoreTest.jsx.html#lineNumber107",
    "Tests Store with action that creates another store from JSON",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/decorators/StoreTest.jsx.html#lineNumber132",
    "Tests Store with action that takes multiple arguments",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/decorators/StoreTest.jsx.html#lineNumber735",
    "Tests Store with array - test unshift, shift, splice, fill, reverse, sort",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/decorators/StoreTest.jsx.html#lineNumber690",
    "Tests Store with double-nested state - action dispatched to sub-store should pass through parent middleware",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/decorators/StoreTest.jsx.html#lineNumber324",
    "Tests Store with double-nested state - action dispatched to sub-store should pass through parent middleware",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/decorators/StoreTest.jsx.html#lineNumber801",
    "Tests Store with map - test delete, clear",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/decorators/StoreTest.jsx.html#lineNumber370",
    "Tests Store with nested state - action dispatched to sub-store inside an array should pass through parent middleware",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/decorators/StoreTest.jsx.html#lineNumber403",
    "Tests Store with nested state - action dispatched to sub-store inside an map should pass through parent middleware",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/decorators/StoreTest.jsx.html#lineNumber264",
    "Tests Store with nested state - action dispatched to sub-store should pass through parent middleware",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/decorators/StoreTest.jsx.html#lineNumber292",
    "Tests Store with nested state - action that dispatches another action to sub-store should only pass through parent middleware once",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/decorators/StoreTest.jsx.html#lineNumber641",
    "Tests Store with nested state - can remove sub-store from a map and add a new one - only new one should get updates",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/decorators/StoreTest.jsx.html#lineNumber493",
    "Tests Store with nested state - can remove sub-store from an array and add a new one - only new one should get updates",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/decorators/StoreTest.jsx.html#lineNumber542",
    "Tests Store with nested state - can remove sub-store from an array by changing length, and add a new one - only new one should get updates",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/decorators/StoreTest.jsx.html#lineNumber436",
    "Tests Store with nested state - can replace sub-store - only new one should get updates",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/decorators/StoreTest.jsx.html#lineNumber592",
    "Tests Store with nested state - can replace sub-store in an array - only new one should get updates",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/decorators/StoreTest.jsx.html#lineNumber198",
    "Tests Store with nested state - dispatched actions should not propagate if parent handler marked as propagate:false",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/decorators/StoreTest.jsx.html#lineNumber230",
    "Tests Store with nested state - dispatched actions should not propagate if parent handler returns a value",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/decorators/StoreTest.jsx.html#lineNumber154",
    "Tests Store with nested state - dispatched actions should propagate",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/decorators/StoreTest.jsx.html#lineNumber83",
    "Tests Store with simple state and basic action - only dispatching will update state",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/middleware/ThunkMiddlewareTest.jsx.html#lineNumber21",
    "Thunk Middleware",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/middleware/ThunkMiddlewareTest.jsx.html#lineNumber235",
    "Thunk Middleware Asynchronous actions can only be dispatched directly - they do not propagate",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/middleware/ThunkMiddlewareTest.jsx.html#lineNumber51",
    "Thunk Middleware Can disable Thunk middleware",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/middleware/ThunkMiddlewareTest.jsx.html#lineNumber183",
    "Thunk Middleware Can dispatch thunk middleware - asynchronous action with @Action({async: true})",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/middleware/ThunkMiddlewareTest.jsx.html#lineNumber209",
    "Thunk Middleware Can dispatch thunk middleware - asynchronous action with @Action({async: true}), where action handler returns a promise",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/middleware/ThunkMiddlewareTest.jsx.html#lineNumber129",
    "Thunk Middleware Can dispatch thunk middleware - asynchronous action with Promises",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/middleware/ThunkMiddlewareTest.jsx.html#lineNumber157",
    "Thunk Middleware Can dispatch thunk middleware - asynchronous action with Promises, where action handler returns a promise",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/middleware/ThunkMiddlewareTest.jsx.html#lineNumber104",
    "Thunk Middleware Can dispatch thunk middleware - asynchronous action with setTimeout",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/middleware/ThunkMiddlewareTest.jsx.html#lineNumber71",
    "Thunk Middleware Can dispatch thunk middleware to a sub-store",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/middleware/ThunkMiddlewareTest.jsx.html#lineNumber23",
    "Thunk Middleware Thunk middleware should be enabled by default",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/DisposableTest.jsx.html#lineNumber20",
    "Utils.Disposable",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/DisposableTest.jsx.html#lineNumber62",
    "Utils.Disposable disposeLink",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/DisposableTest.jsx.html#lineNumber54",
    "Utils.Disposable disposes a function",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/DisposableTest.jsx.html#lineNumber22",
    "Utils.Disposable disposes children",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/DisposableTest.jsx.html#lineNumber48",
    "Utils.Disposable set disposables, but then try to unlink a non-child",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/DisposableTest.jsx.html#lineNumber71",
    "Utils.Disposable tree of disposables",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/DisposableTest.jsx.html#lineNumber32",
    "Utils.Disposable unlink",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/DisposableTest.jsx.html#lineNumber42",
    "Utils.Disposable unlink when no disposables exist (should not throw)",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/ObservableArrayTest.jsx.html#lineNumber19",
    "Utils.ObservableArray",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/ObservableArrayTest.jsx.html#lineNumber176",
    "Utils.ObservableArray overrides Array methods which return a new instance of array properly",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/ObservableArrayTest.jsx.html#lineNumber207",
    "Utils.ObservableArray overrides Array mutators returning array properly",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/ObservableArrayTest.jsx.html#lineNumber155",
    "Utils.ObservableArray overrides Array.prototype.concat properly",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/ObservableArrayTest.jsx.html#lineNumber134",
    "Utils.ObservableArray removeItem deletes one item and updates bindings",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/ObservableArrayTest.jsx.html#lineNumber77",
    "Utils.ObservableArray resizing array to larger size does not affect previous bindings",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/ObservableArrayTest.jsx.html#lineNumber62",
    "Utils.ObservableArray resizing array to same size has no effect",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/ObservableArrayTest.jsx.html#lineNumber96",
    "Utils.ObservableArray resizing array to smaller size changes bindings to truncated values",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/ObservableArrayTest.jsx.html#lineNumber51",
    "Utils.ObservableArray round trips active arrays to native arrays and back",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/ObservableArrayTest.jsx.html#lineNumber36",
    "Utils.ObservableArray setAt() changes value and signals the change",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/ObservableArrayTest.jsx.html#lineNumber115",
    "Utils.ObservableArray swapped values affect bindings",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/ObservableArrayTest.jsx.html#lineNumber228",
    "Utils.ObservableArray toArray() triggers bindings",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/ObservableArrayTest.jsx.html#lineNumber21",
    "Utils.ObservableArray updates to ObservableArray by mutators should invalidate jsx",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/ObservableMapTest.jsx.html#lineNumber19",
    "Utils.ObservableMap",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/ObservableMapTest.jsx.html#lineNumber63",
    "Utils.ObservableMap can clear an observable map",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/ObservableMapTest.jsx.html#lineNumber42",
    "Utils.ObservableMap can create an ObservableMap out of an array-constructed Map",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/ObservableMapTest.jsx.html#lineNumber35",
    "Utils.ObservableMap can create an ObservableMap out of non-map data",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/ObservableMapTest.jsx.html#lineNumber21",
    "Utils.ObservableMap can create an empty ObservableMap and modify it",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/ObservableMapTest.jsx.html#lineNumber49",
    "Utils.ObservableMap can delete elements from an observable map",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/ObservableMapTest.jsx.html#lineNumber72",
    "Utils.ObservableMap swapped values affect bindings",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/ObservableSetTest.jsx.html#lineNumber19",
    "Utils.ObservableSet",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/ObservableSetTest.jsx.html#lineNumber41",
    "Utils.ObservableSet can create an ObservableSet out of an array-constructed Set",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/ObservableSetTest.jsx.html#lineNumber33",
    "Utils.ObservableSet can create an ObservableSet out of an iterable object",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/ObservableSetTest.jsx.html#lineNumber21",
    "Utils.ObservableSet can create an empty ObservableSet and modify it",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/ObservableSetTest.jsx.html#lineNumber48",
    "Utils.ObservableSet swapped values affect bindings",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/SignalDispatcherTest.jsx.html#lineNumber25",
    "Utils.SignalDispatcher",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/SignalDispatcherTest.jsx.html#lineNumber27",
    "Utils.SignalDispatcher call watch() on an observable",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/SignalDispatcherTest.jsx.html#lineNumber52",
    "Utils.SignalDispatcher call watch() on an observable - ignore first run",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/SignalDispatcherTest.jsx.html#lineNumber69",
    "Utils.SignalDispatcher call watchCollection() on an observable array",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/SignalDispatcherTest.jsx.html#lineNumber95",
    "Utils.SignalDispatcher call watchCollection() on an observable array - ignore first run",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/SignalDispatcherTest.jsx.html#lineNumber248",
    "Utils.SignalDispatcher dispose should call stopListening",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/SignalDispatcherTest.jsx.html#lineNumber150",
    "Utils.SignalDispatcher should be able define an observable and watch it",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/SignalDispatcherTest.jsx.html#lineNumber212",
    "Utils.SignalDispatcher should be able to trigger an event and listen for it with listenTo/stopListening",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/SignalDispatcherTest.jsx.html#lineNumber182",
    "Utils.SignalDispatcher should be able to trigger an event and listen for it with on/off",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/SignalDispatcherTest.jsx.html#lineNumber131",
    "Utils.SignalDispatcher watches should not trigger after disposing signal dispatcher",
    "test"
  ],
  [
    "",
    "test-file/@twist/core/test/SignalDispatcherTest.jsx.html#lineNumber112",
    "Utils.SignalDispatcher watches should not trigger after disposing watch",
    "test"
  ]
]